FIX-Failed-Test-Components
jorgecarmona/telco pull request #10
Opened 2024-07-19 22:21 UTC by davidc0326

"Increase test coverage for components to over 80%

![image](https://github.com/user-attachments/assets/1ba29367-8f3f-41b8-b594-af2eebcfb12c)

2024-07-21 20:17 UTC, SGutierrez17 commented on src/atoms/icon.tsx
> +const Icon: React.FC<IconProps> = ({
Ingeniero así nosotros nos creamos las funciones.

2024-07-21 20:18 UTC, SGutierrez17 requested changes
Ingeniero te deje comentario

2024-07-24 20:27 UTC, SGutierrez17 approved these changes
Good job!

2024-07-24 20:54 UTC, juanav22 approved these changes
Good Job

2024-07-24 20:56 UTC, merged