creation of skeleton component
jorgecarmona/telco pull request #18
Opened 2024-07-23 01:34 UTC by napito27

Created the Skeleton Component.
 
![image](https://github.com/user-attachments/assets/68a02aa6-252b-470e-a5b8-875b338d1ad9)

2024-07-24 20:29 UTC, SGutierrez17 commented
Ingeniero napo, podrias arreglar el conflicto que tienes para poder revisar el componente

2024-07-24 21:17 UTC, SGutierrez17 commented
Ingeniero napo, podrias enviar el coverage para verificar que cumple con el requerimiento minimo, gracias.

2024-07-24 21:21 UTC, SGutierrez17 commented on src/atoms/__tests__/skeleton.test.tsx
> +import '@testing-library/jest-dom/extend-expect';
Ingeniero no necesitas hacer esta importación, solo eliminala y deja ese salto de linea

2024-07-24 21:21 UTC, SGutierrez17 commented on src/stories/atoms/skeleton.stories.tsx
> +import { Meta, StoryObj } from '@storybook/react';
Dale un salto de linea

2024-07-24 21:22 UTC, SGutierrez17 commented on src/stories/atoms/skeleton.stories.tsx
> +import { Avatar, Box } from '@mui/material';
Ingeniero usa el componente de avatar nuestro

2024-07-24 21:22 UTC, SGutierrez17 requested changes
Ingeniero revisa por favor los comentarios

2024-07-25 02:52 UTC, SGutierrez17 approved these changes
Good Job!

2024-07-25 13:04 UTC, NancyBlancoS approved these changes

2024-07-25 16:30 UTC, NancyBlancoS requested changes

2024-07-25 16:30 UTC, NancyBlancoS commented on src/stories/atoms/skeleton.stories.tsx
> +      control: { disable: true },
If  we are not going to let the children be modified, wouldn't it be better to just not show it in the stortybook?
with `table: {disable: true}`
What do you think?

2024-07-28 16:56 UTC, NancyBlancoS approved these changes
Great job!!

2024-07-29 15:42 UTC, SGutierrez17 commented
Ingeniero Arregla los conflictos para hacer el merge

2024-07-29 21:07 UTC, merged