Feat/telco 53 create pagination data grid component
jorgecarmona/telco pull request #23
Opened 2024-07-26 18:53 UTC by OskarMantilla21

Create [Pagination](https://mui.com/x/react-data-grid/pagination/) component: It allows data to be divided into pages, facilitating navigation and improving performance when loading large data sets.

2024-07-29 15:43 UTC, SGutierrez17 commented on src/atoms/data-grid.tsx
> +import React, {useState} from 'react';
Salto de linea

2024-07-29 15:44 UTC, SGutierrez17 requested changes
Ingeniero te hice comentario

2024-07-29 16:10 UTC, OskarMantilla21 commented on src/atoms/data-grid.tsx
> +import React, {useState} from 'react';
![image](https://github.com/user-attachments/assets/c05a4e20-e421-4fd9-885a-a4affff6eac0)

2024-07-29 16:15 UTC, NancyBlancoS commented
Ing, could you please add and example of use to check it please?

2024-07-30 13:13 UTC, NancyBlancoS approved these changes

2024-07-31 16:45 UTC, SGutierrez17 approved these changes
Ingeniero esta bien, solo recuerda que estamos manejando todo en orden alfabetico y asi como lo pones en el interface tambien lo manejamos al momento de usar las props

2024-07-31 16:47 UTC, SGutierrez17 commented
Resuelve los conflictos para poder hacer el merge

2024-08-01 14:55 UTC, closed without merging