create sorting data grid component
jorgecarmona/telco pull request #24
Opened 2024-07-26 21:34 UTC by davidc0326

- Added DataGrid component with sorting functionality.
- Removed pagination logic to focus on sorting.

2024-07-30 00:27 UTC, napito27 approved these changes
Looks good

2024-07-31 16:40 UTC, SGutierrez17 commented on src/atoms/data-grid.tsx
> +import {
Salto de linea

2024-07-31 16:41 UTC, SGutierrez17 requested changes
Ingeniero buenos dias, te hice un comentario y adicional adjunto el link donde vamos a guiarnos para tener la estructura de organizacion adecuada

https://github.com/jorgecarmona/codigoingeniero/wiki/React-Coding-Guidelines

2024-07-31 16:48 UTC, SGutierrez17 commented
Ingeniero resuelve los conflictos que tienes

2024-07-31 21:45 UTC, SGutierrez17 approved these changes

2024-07-31 21:46 UTC, merged